name: CD-BETA
on:
  push:
    branches: [beta]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - name: Write SSH keys
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVKEY_BETA }}" > ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.BETA_HOST }} > ~/.ssh/known_hosts

      - name: deploy
        run:
          ssh -i ~/.ssh/id_rsa ${{ secrets.APP_USER }}@${{ secrets.BETA_HOST }}
          "/opt/git-sync.sh"
